server:
  port: 8086

spring:
  application:
    name: HRA-api-gateway
  cloud:
    gateway:
      routes:
        - id: property-service
          uri: http://localhost:8088
          predicates:
            - Path=/properties/buildings/**,/properties/flats/**
            - Path=/users/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka