server:
  port: 8086

spring:
  application:
    name: HRA-api-gateway
  cloud:
    gateway:
      routes:
        - id: property-service
          uri: http://localhost:8088
          predicates:
            - Path=/properties/buildings/**,/properties/flats/**
            - Path=/users/**
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false