server:
  port: 8085   # or any free port

spring:
  application:
    name: analytics-service

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: siva
    password: siva
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update       # or validate/create/update as you prefer
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

